services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: backend
    # wait until the db is ready
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - APP_SECRET=${APP_SECRET}
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    image: frontend
    ports:
      - "${APP_PORT}:80"
    # wait until db is ready
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # check whether the db is ready or not
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME} -p ${DB_PORT}"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data: