const keybinds = new Map<string, string>();

keybinds.set("j", "U");
keybinds.set("f", "U'");
keybinds.set("i", "R");
keybinds.set("k", "R'");
keybinds.set("d", "L");
keybinds.set("e", "L'");
keybinds.set("s", "D");
keybinds.set("l", "D'");
keybinds.set(",", "Uw");
keybinds.set("c", "Uw'");
keybinds.set("u", "Rw");
keybinds.set("m", "Rw'");
keybinds.set("b", "x'");
keybinds.set("n", "x'");
keybinds.set("t", "x");
keybinds.set("y", "x");
keybinds.set("r", "Lw'");
keybinds.set("v", "Lw");
keybinds.set("g", "F'");
keybinds.set("h", "F");
keybinds.set(";", "y");
keybinds.set("a", "y'");
keybinds.set("p", "z");
keybinds.set("q", "z'");
keybinds.set("w", "B");
keybinds.set("o", "B'");
keybinds.set(".", "m'");
keybinds.set("x", "m'");
keybinds.set("z", "Dw");
keybinds.set("/", "Dw'");
keybinds.set("5", "m");
keybinds.set("6", "m");

export default keybinds;